<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>Trakit.Objects</RootNamespace>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>Trak-iT API Object Model</Title>
		<PackageProjectUrl>https://apis.trakit.ca/dotnet</PackageProjectUrl>
		<AssemblyName>Trakit.$(MSBuildProjectName)</AssemblyName>
		<AssemblyVersion>0.4.0.5</AssemblyVersion>
		<FileVersion>0.4.0.5</FileVersion>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>0.4.0.5</Version>
		<PackageIcon>trakit-objects.png</PackageIcon>
		<Copyright>2024 Traki-iT Wireless Inc.</Copyright>
		<Authors>Trak-it Wireless Inc.</Authors>
	</PropertyGroup>
	<ItemGroup>
		<None Update="trakit-objects.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>
</Project>